/**
 * Dịch tên cấu trúc BodyParts3D sang tiếng Việt bằng cách GHÉP thuật ngữ.
 *
 * ## Vì sao ghép chứ không dịch từng tên
 *
 * 3.432 tên của bộ dữ liệu được dựng từ khoảng 1.400 cụm gốc theo vài khuôn
 * cố định: "<cụm> of <cụm>", tiền tố left/right, số thứ tự ("fifth thoracic
 * vertebra"). Dịch cụm gốc một lần rồi ghép thì một chỗ sửa ("artery") đúng ở
 * mọi tên chứa nó, và tên nào có cụm chưa dịch thì trả `null` — người đọc
 * thấy tên tiếng Anh gốc, không thấy nửa câu tiếng Việt ghép dở.
 *
 * Tiếng Việt đặt định ngữ sau danh từ, nên "X of Y" → "X Y"
 * ("branch of right coronary artery" → "nhánh động mạch vành phải"), và
 * left/right đứng ngay sau cụm nó bổ nghĩa.
 *
 * ## Độ tin cậy
 *
 * Bảng này dịch có hỗ trợ của AI theo danh pháp giải phẫu tiếng Việt thông
 * dụng, CHƯA qua duyệt chuyên môn — vì thế UI luôn hiện tên tiếng Anh gốc
 * ngay dưới, và ghi rõ trong phần "Nguồn & ghi công". Mục đã duyệt tay nằm ở
 * `VI_NAMES` (`names-vi.ts`) và luôn thắng bảng này. Nhóm cụm chỉ là khái niệm
 * phân loại của ontology FMA ("anatomical entity", "cardinal organ part") được
 * dịch sát nghĩa đen; chúng hiếm khi là thứ người đọc chạm vào.
 */

const T: Record<string, string> = {
  // ------------------------------------------------------------- A
  abdomen: "bụng",
  "abdomen proper": "bụng (phần chính)",
  "abdominal aorta": "động mạch chủ bụng",
  "abdominal part": "phần bụng",
  "abdominal segment": "đoạn bụng",
  "abductor digiti minimi": "cơ dạng ngón út",
  "abductor hallucis": "cơ dạng ngón chân cái",
  "abductor pollicis brevis": "cơ dạng ngón cái ngắn",
  "abductor pollicis longus": "cơ dạng ngón cái dài",
  "accessory hemiazygos vein": "tĩnh mạch bán đơn phụ",
  "accessory subsuperior branch": "nhánh dưới đỉnh phụ",
  "acromial branch": "nhánh cùng vai",
  "acromial part": "phần cùng vai",
  "adductor brevis": "cơ khép ngắn",
  "adductor hallucis": "cơ khép ngón chân cái",
  "adductor longus": "cơ khép dài",
  "adductor magnus": "cơ khép lớn",
  "adductor minimus": "cơ khép bé",
  "adductor pollicis": "cơ khép ngón cái",
  "adrenal gland": "tuyến thượng thận",
  "alimentary system": "hệ tiêu hoá",
  amygdala: "hạnh nhân",
  "anal part": "phần hậu môn",
  anastomosis: "nhánh nối",
  "anatomical boundary entity": "thực thể ranh giới giải phẫu",
  "anatomical cavity": "khoang giải phẫu",
  "anatomical cluster": "cụm giải phẫu",
  "anatomical compartment space": "khoang ngăn giải phẫu",
  "anatomical conduit space": "khoang ống dẫn giải phẫu",
  "anatomical entity": "thực thể giải phẫu",
  "anatomical junction": "chỗ nối giải phẫu",
  "anatomical line": "đường giải phẫu",
  "anatomical lobe": "thùy giải phẫu",
  "anatomical set": "tập hợp giải phẫu",
  "anatomical space": "không gian giải phẫu",
  "anatomical structure": "cấu trúc giải phẫu",
  anconeus: "cơ khuỷu",
  "angular gyrus": "hồi góc",
  "anterior abdominal wall": "thành bụng trước",
  "anterior basal bronchopulmonary segment": "phân thùy đáy trước",
  "anterior basal segmental artery": "động mạch phân thùy đáy trước",
  "anterior basal segmental bronchial tree": "cây phế quản phân thùy đáy trước",
  "anterior basal segmental vein": "tĩnh mạch phân thùy đáy trước",
  "anterior branch": "nhánh trước",
  "anterior bronchopulmonary segment": "phân thùy trước",
  "anterior cardiac vein": "tĩnh mạch tim trước",
  "anterior cardiac venous tree": "cây tĩnh mạch tim trước",
  "anterior cecal artery": "động mạch manh tràng trước",
  "anterior cerebral artery": "động mạch não trước",
  "anterior cervical intertransversarii": "các cơ gian ngang cổ trước",
  "anterior chamber": "tiền phòng",
  "anterior chest": "ngực trước",
  "anterior chest wall": "thành ngực trước",
  "anterior choroidal artery": "động mạch mạch mạc trước",
  "anterior circumflex humeral artery": "động mạch mũ cánh tay trước",
  "anterior circumflex humeral vein": "tĩnh mạch mũ cánh tay trước",
  "anterior commissure": "mép trước",
  "anterior communicating artery": "động mạch thông trước",
  "anterior compartment": "khoang trước",
  "anterior cusp": "lá van trước",
  "anterior descending branch": "nhánh xuống trước",
  "anterior division": "ngành trước",
  "anterior ethmoidal nerve": "thần kinh sàng trước",
  "anterior inferior cerebellar artery": "động mạch tiểu não trước dưới",
  "anterior inferior pancreaticoduodenal artery": "động mạch tá tụy dưới trước",
  "anterior inferior segmental branch": "nhánh phân thùy trước dưới",
  "anterior inferior segmental hepatic artery": "động mạch gan phân thùy trước dưới",
  "anterior inferior segmental tributary": "nhánh phân thùy trước dưới",
  "anterior inferior tributary": "nhánh trước dưới",
  "anterior intercostal veins": "các tĩnh mạch gian sườn trước",
  "anterior interosseous artery": "động mạch gian cốt trước",
  "anterior interventricular artery": "động mạch gian thất trước",
  "anterior interventricular branch": "nhánh gian thất trước",
  "anterior interventricular vein": "tĩnh mạch gian thất trước",
  "anterior leaflet": "lá van trước",
  "anterior mediastinum": "trung thất trước",
  "anterior papillary muscle": "cơ nhú trước",
  "anterior parietal artery": "động mạch đỉnh trước",
  "anterior part": "phần trước",
  "anterior sector": "phân khu trước",
  "anterior segmental artery": "động mạch phân thùy trước",
  "anterior segmental bronchial tree": "cây phế quản phân thùy trước",
  "anterior segmental hepatic artery": "động mạch gan phân thùy trước",
  "anterior segmental vein": "tĩnh mạch phân thùy trước",
  "anterior spinal artery": "động mạch tủy sống trước",
  "anterior suboccipital muscle": "cơ dưới chẩm trước",
  "anterior superficial chest wall": "thành ngực nông trước",
  "anterior superior pancreaticoduodenal artery": "động mạch tá tụy trên trước",
  "anterior superior segmental branch": "nhánh phân thùy trước trên",
  "anterior superior segmental hepatic artery": "động mạch gan phân thùy trước trên",
  "anterior superior segmental tributary": "nhánh phân thùy trước trên",
  "anterior superior tributary": "nhánh trước trên",
  "anterior temporal artery": "động mạch thái dương trước",
  "anterior temporal branch": "nhánh thái dương trước",
  "anterior thoracic wall": "thành ngực trước",
  "anterior tibial artery": "động mạch chày trước",
  "anterior tibial recurrent artery": "động mạch quặt ngược chày trước",
  "anterior tibial vein": "tĩnh mạch chày trước",
  "anterior tributary": "nhánh trước",
  "anterior ulnar recurrent artery": "động mạch quặt ngược trụ trước",
  "anterior ventricular branch": "nhánh thất trước",
  "anterior wall": "thành trước",
  "antero-medial basal segmental artery": "động mạch phân thùy đáy trước trong",
  "anterolateral central branch": "nhánh trung tâm trước ngoài",
  "anterolateral head": "đầu trước ngoài",
  aorta: "động mạch chủ",
  "aortic valve": "van động mạch chủ",
  "apical bronchopulmonary segment": "phân thùy đỉnh",
  "apical part": "phần đỉnh",
  "apical segmental artery": "động mạch phân thùy đỉnh",
  "apical segmental bronchial tree": "cây phế quản phân thùy đỉnh",
  "apical segmental vein": "tĩnh mạch phân thùy đỉnh",
  "apicoposterior bronchopulmonary segment": "phân thùy đỉnh sau",
  "apicoposterior division": "ngành đỉnh sau",
  "apicoposterior segmental vein": "tĩnh mạch phân thùy đỉnh sau",
  "appendicular artery": "động mạch ruột thừa",
  appendix: "ruột thừa",
  arch: "cung",
  archicortex: "vỏ não cổ",
  "arcuate artery": "động mạch cung",
  arm: "cánh tay",
  "arteria princeps pollicis": "động mạch chính ngón cái",
  "arteria radialis indicis": "động mạch quay ngón trỏ",
  "arterial anastomosis": "nhánh nối động mạch",
  "arterial tree organ": "cây động mạch",
  "arterial trunk": "thân động mạch",
  arteries: "các động mạch",
  artery: "động mạch",
  "articular disk": "đĩa khớp",
  aryepiglotticus: "cơ phễu nắp thanh môn",
  "arytenoid cartilage": "sụn phễu",
  "ascending aorta": "động mạch chủ lên",
  "ascending branch": "nhánh lên",
  "ascending colon": "đại tràng lên",
  "ascending lumbar vein": "tĩnh mạch thắt lưng lên",
  "ascending part": "phần lên",
  atlas: "đốt đội",
  atrium: "tâm nhĩ",
  "atypical rib": "xương sườn không điển hình",
  "auriculotemporal part": "phần tai thái dương",
  "autonomic ganglion": "hạch tự chủ",
  "axial skeletal system": "hệ xương trục",
  "axial skeleton": "bộ xương trục",
  "axillary artery": "động mạch nách",
  "axillary vein": "tĩnh mạch nách",
  axis: "đốt trục",
  "azygos vein": "tĩnh mạch đơn",

  // ------------------------------------------------------------- B
  back: "lưng",
  "basal branch": "nhánh đáy",
  "basal ganglion": "hạch nền",
  "basal segmental artery": "động mạch phân thùy đáy",
  "basal segmental bronchial tree": "cây phế quản phân thùy đáy",
  "basicranial part": "phần nền sọ",
  basicranium: "nền sọ",
  "basilar artery": "động mạch nền",
  "basilic vein": "tĩnh mạch nền",
  "biceps brachii": "cơ nhị đầu cánh tay",
  "biceps femoris": "cơ nhị đầu đùi",
  "big toe": "ngón chân cái",
  "bile duct": "ống mật",
  "biliary tree": "cây đường mật",
  body: "thân",
  "body cavity content": "thành phần khoang cơ thể",
  "body compartment": "khoang cơ thể",
  "body proper": "cơ thể (phần chính)",
  "body wall": "thành cơ thể",
  "bone organ": "xương",
  "bony part": "phần xương",
  "bony pectoral girdle": "đai ngực (phần xương)",
  "bony pelvis": "khung chậu xương",
  "brachial artery": "động mạch cánh tay",
  "brachial vein": "tĩnh mạch cánh tay",
  brachialis: "cơ cánh tay",
  "brachiocephalic artery": "thân cánh tay đầu",
  "brachiocephalic vein": "tĩnh mạch cánh tay đầu",
  brachioradialis: "cơ cánh tay quay",
  brachium: "cánh tay",
  brain: "não",
  brainstem: "thân não",
  branch: "nhánh",
  "bronchial artery": "động mạch phế quản",
  "bronchial branch": "nhánh phế quản",
  "bronchial tree": "cây phế quản",
  bronchus: "phế quản",

  // ------------------------------------------------------------- C
  "calcaneal branches": "các nhánh gót",
  "calcaneal tendon": "gân gót",
  calcaneus: "xương gót",
  "callosomarginal artery": "động mạch viền thể chai",
  "canine tooth": "răng nanh",
  capitate: "xương cả",
  capsule: "bao",
  "cardiac chamber": "buồng tim",
  "cardiac valve": "van tim",
  "cardiac vein": "tĩnh mạch tim",
  "cardinal body part": "phần cơ thể chính",
  "cardinal organ part": "phần cơ quan chính",
  "cardinal segment": "đoạn chính",
  "cardinal tissue part": "phần mô chính",
  "cardiovascular system": "hệ tim mạch",
  "carpal bone": "xương cổ tay",
  "cartilage organ": "sụn",
  "cartilage organ component": "thành phần sụn",
  "cartilaginous part": "phần sụn",
  "cartilaginous skeleton": "khung sụn",
  "caudal pancreatic artery": "động mạch đuôi tụy",
  "caudate lobe": "thùy đuôi",
  "caudate lobe branch": "nhánh thùy đuôi",
  "caudate lobe tributary": "nhánh thùy đuôi",
  "caudate nucleus": "nhân đuôi",
  "cavernous organ": "cơ quan hang",
  "cavitated organ": "cơ quan có khoang",
  "cavitated organ parts": "các phần cơ quan có khoang",
  cavity: "khoang",
  cecum: "manh tràng",
  "celiac artery": "động mạch thân tạng",
  "celiac trunk": "thân tạng",
  "cell part cluster": "cụm thành phần tế bào",
  "central canal": "ống trung tâm",
  "central sulcus": "rãnh trung tâm",
  "cephalic vein": "tĩnh mạch đầu",
  cerebellum: "tiểu não",
  "cerebral aqueduct": "cống não",
  "cerebral arterial circle": "vòng động mạch não",
  "cerebral cortex": "vỏ đại não",
  "cerebral hemisphere": "bán cầu đại não",
  "cerebral part": "phần não",
  "cerebral white matter": "chất trắng đại não",
  "cervical intervertebral symphysis": "khớp gian đốt sống cổ",
  "cervical rotator": "cơ xoay cổ",
  "cervical vertebra": "đốt sống cổ",
  "cervical vertebrae": "các đốt sống cổ",
  "cervical vertebral column": "cột sống cổ",
  chamber: "buồng",
  "check ligament": "dây chằng hãm",
  cheek: "má",
  chest: "ngực",
  "chest wall": "thành ngực",
  choroid: "màng mạch",
  "choroid plexus": "đám rối mạch mạc",
  "ciliary body": "thể mi",
  "ciliary ganglion": "hạch mi",
  "cingulate gyrus": "hồi đai",
  "circumflex branch": "nhánh mũ",
  "circumflex scapular artery": "động mạch mũ vai",
  "circumflex scapular vein": "tĩnh mạch mũ vai",
  "circumventricular organ": "cơ quan quanh não thất",
  clavicle: "xương đòn",
  "clavicular part": "phần đòn",
  coccygeus: "cơ cụt",
  "coeliac artery": "động mạch thân tạng",
  "colic artery": "động mạch đại tràng",
  "colic vein": "tĩnh mạch đại tràng",
  colon: "đại tràng",
  commissure: "mép",
  "common basal vein": "tĩnh mạch đáy chung",
  "common carotid artery": "động mạch cảnh chung",
  "common hepatic artery": "động mạch gan chung",
  "common hepatic duct": "ống gan chung",
  "common iliac artery": "động mạch chậu chung",
  "common iliac vein": "tĩnh mạch chậu chung",
  "common interosseous artery": "động mạch gian cốt chung",
  "common palmar digital artery": "động mạch gan ngón tay chung",
  "common palmar digital vein": "tĩnh mạch gan ngón tay chung",
  "common plantar digital arteries": "các động mạch gan ngón chân chung",
  "common tendinous ring": "vòng gân chung",
  "communicating branch": "nhánh thông",
  compartment: "khoang",
  "connective tissue": "mô liên kết",
  "constrictor muscle": "cơ khít",
  content: "thành phần chứa",
  continuity: "chỗ liên tục",
  "conus artery": "động mạch nón",
  "conus branch": "nhánh nón",
  "conus elasticus": "nón đàn hồi",
  coracobrachialis: "cơ quạ cánh tay",
  cornea: "giác mạc",
  "corniculate cartilage": "sụn sừng",
  "corona ciliaris": "vành mi",
  "coronary artery": "động mạch vành",
  "coronary sinus": "xoang tĩnh mạch vành",
  "coronary sinus tree": "cây xoang tĩnh mạch vành",
  "corpus callosum": "thể chai",
  "corpus cavernosum": "vật hang",
  "corpus spongiosum": "vật xốp",
  cortex: "vỏ",
  "corticomedullary organ": "cơ quan vỏ tủy",
  "costal cartilage": "sụn sườn",
  "costocervical artery": "động mạch sườn cổ",
  "costocervical trunk": "thân sườn cổ",
  "cranial dura mater": "màng cứng sọ",
  "cranial nerve": "thần kinh sọ",
  "cranial parasympathetic ganglion": "hạch đối giao cảm sọ",
  "cricoid cartilage": "sụn nhẫn",
  cricothyroid: "cơ nhẫn giáp",
  "cricothyroid ligament": "dây chằng nhẫn giáp",
  "cuboid bone": "xương hộp",
  "cuneiform bone": "xương chêm",
  "cuneiform cartilage": "sụn chêm",
  cusp: "lá van",
  "cystic duct": "ống túi mật",

  // ------------------------------------------------------------- D
  decussation: "bắt chéo",
  "deep brachial artery": "động mạch cánh tay sâu",
  "deep cervical artery": "động mạch cổ sâu",
  "deep dorsal vein": "tĩnh mạch mu sâu",
  "deep extrinsic muscle": "cơ ngoại lai sâu",
  "deep fascial system": "hệ mạc sâu",
  "deep femoral artery": "động mạch đùi sâu",
  "deep femoral vein": "tĩnh mạch đùi sâu",
  "deep muscle": "cơ sâu",
  "deep palmar arch": "cung gan tay sâu",
  "deep palmar arterial arch": "cung động mạch gan tay sâu",
  "deep palmar venous arch": "cung tĩnh mạch gan tay sâu",
  "deep plantar artery": "động mạch gan chân sâu",
  "deep postvertebral muscle": "cơ sau cột sống sâu",
  "deferent duct": "ống dẫn tinh",
  deltoid: "cơ delta",
  "deltoid branch": "nhánh delta",
  "descending aorta": "động mạch chủ xuống",
  "descending branch": "nhánh xuống",
  "descending colon": "đại tràng xuống",
  "descending genicular artery": "động mạch gối xuống",
  "descending part": "phần xuống",
  "descending thoracic aorta": "động mạch chủ ngực xuống",
  "diagonal branch": "nhánh chéo",
  diaphragm: "cơ hoành",
  diencephalon: "gian não",
  digastric: "cơ hai bụng",
  "digital artery": "động mạch ngón",
  "distal carpal bone": "xương cổ tay hàng xa",
  "distal part": "phần xa",
  "distal perforating artery": "động mạch xuyên xa",
  "distal phalanx": "đốt xa",
  "dorsal artery": "động mạch mu",
  "dorsal carpal branch": "nhánh mu cổ tay",
  "dorsal digital arteries": "các động mạch mu ngón",
  "dorsal digital artery": "động mạch mu ngón",
  "dorsal digital veins": "các tĩnh mạch mu ngón",
  "dorsal interossei": "các cơ gian cốt mu",
  "dorsal metacarpal arteries": "các động mạch mu đốt bàn tay",
  "dorsal metacarpal vein": "tĩnh mạch mu đốt bàn tay",
  "dorsal pancreatic artery": "động mạch tụy lưng",
  "dorsal scapular artery": "động mạch lưng vai",
  "dorsal venous arch": "cung tĩnh mạch mu",
  "dorsal venous network": "mạng tĩnh mạch mu",
  "dorsalis pedis artery": "động mạch mu chân",
  dorsum: "mu",
  duct: "ống",
  duodenum: "tá tràng",
  "dura mater": "màng cứng",

  // ------------------------------------------------------------- E
  "endocrine system": "hệ nội tiết",
  epidermis: "biểu bì",
  epididymis: "mào tinh",
  epiglottis: "nắp thanh môn",
  epithalamus: "vùng trên đồi",
  epithelium: "biểu mô",
  "esophageal artery": "động mạch thực quản",
  esophagus: "thực quản",
  ethmoid: "xương sàng",
  "extensor carpi radialis brevis": "cơ duỗi cổ tay quay ngắn",
  "extensor carpi radialis longus": "cơ duỗi cổ tay quay dài",
  "extensor carpi ulnaris": "cơ duỗi cổ tay trụ",
  "extensor digiti minimi": "cơ duỗi ngón út",
  "extensor digitorum": "cơ duỗi các ngón",
  "extensor digitorum longus": "cơ duỗi các ngón chân dài",
  "extensor hallucis brevis": "cơ duỗi ngón chân cái ngắn",
  "extensor hallucis longus": "cơ duỗi ngón chân cái dài",
  "extensor indicis": "cơ duỗi ngón trỏ",
  "extensor pollicis brevis": "cơ duỗi ngón cái ngắn",
  "extensor pollicis longus": "cơ duỗi ngón cái dài",
  "external anal sphincter": "cơ thắt hậu môn ngoài",
  "external ear": "tai ngoài",
  "external iliac artery": "động mạch chậu ngoài",
  "external iliac artery proper": "động mạch chậu ngoài (phần chính)",
  "external iliac vein": "tĩnh mạch chậu ngoài",
  "external intercostal muscle": "cơ gian sườn ngoài",
  "external jugular vein": "tĩnh mạch cảnh ngoài",
  "external nose": "mũi ngoài",
  "external oblique": "cơ chéo bụng ngoài",
  "extra-ocular muscle": "cơ ngoài nhãn cầu",
  "extrahepatic bile duct": "đường mật ngoài gan",
  "extrinsic ligament": "dây chằng ngoại lai",
  "extrinsic muscle": "cơ ngoại lai",
  eye: "mắt",
  eyeball: "nhãn cầu",
  eyebrow: "lông mày",
  eyelid: "mí mắt",

  // ------------------------------------------------------------- F
  face: "mặt",
  "facial hairs": "lông mặt",
  "false rib": "xương sườn giả",
  "fascia lata": "mạc đùi",
  "faucial part": "phần eo họng",
  "femoral artery": "động mạch đùi",
  "femoral vein": "tĩnh mạch đùi",
  femur: "xương đùi",
  "fibrous layer": "lớp xơ",
  "fibrous ring": "vòng xơ",
  "fibrous skeleton": "khung xơ",
  fibula: "xương mác",
  "fibular vein": "tĩnh mạch mác",
  "fibularis brevis": "cơ mác ngắn",
  "fibularis longus": "cơ mác dài",
  "fibularis tertius": "cơ mác ba",
  finger: "ngón tay",
  "flat bone": "xương dẹt",
  "flexor accessorius": "cơ vuông gan chân",
  "flexor carpi radialis": "cơ gấp cổ tay quay",
  "flexor carpi ulnaris": "cơ gấp cổ tay trụ",
  "flexor digiti minimi brevis": "cơ gấp ngón út ngắn",
  "flexor digitorum brevis": "cơ gấp các ngón chân ngắn",
  "flexor digitorum longus": "cơ gấp các ngón chân dài",
  "flexor digitorum profundus": "cơ gấp các ngón sâu",
  "flexor digitorum superficialis": "cơ gấp các ngón nông",
  "flexor hallucis brevis": "cơ gấp ngón chân cái ngắn",
  "flexor hallucis longus": "cơ gấp ngón chân cái dài",
  "flexor pollicis brevis": "cơ gấp ngón cái ngắn",
  "flexor pollicis longus": "cơ gấp ngón cái dài",
  "flexor retinaculum": "mạc hãm gân gấp",
  "floating rib": "xương sườn cụt",
  foot: "bàn chân",
  "foot proper": "bàn chân (phần chính)",
  forearm: "cẳng tay",
  forebrain: "não trước",
  fornix: "vòm não",
  "fourth ventricle": "não thất tư",
  "free lower limb": "chi dưới tự do",
  "free upper limb": "chi trên tự do",
  "free wall": "thành tự do",
  "frontal bone": "xương trán",
  "frontal lobe": "thùy trán",
  "frontal nerve": "thần kinh trán",
  "frontal part": "phần trán",
  "fusiform gyrus": "hồi hình thoi",

  // ------------------------------------------------------------- G
  gallbladder: "túi mật",
  ganglion: "hạch",
  "gastric artery": "động mạch vị",
  "gastric vein": "tĩnh mạch vị",
  "gastro-epiploic artery": "động mạch vị mạc nối",
  gastrocnemius: "cơ bụng chân",
  "gastroduodenal artery": "động mạch vị tá tràng",
  "gastroepiploic vein": "tĩnh mạch vị mạc nối",
  "gastrointestinal tract": "ống tiêu hoá",
  gemellus: "cơ sinh đôi",
  "gemellus inferior": "cơ sinh đôi dưới",
  "gemellus superior": "cơ sinh đôi trên",
  "genicular vein": "tĩnh mạch gối",
  genioglossus: "cơ cằm lưỡi",
  geniohyoid: "cơ cằm móng",
  "genital system": "hệ sinh dục",
  gingiva: "lợi",
  "glans penis": "quy đầu",
  "globus pallidus": "cầu nhạt",
  "gluteal muscle": "cơ mông",
  "gluteus maximus": "cơ mông lớn",
  "gluteus medius": "cơ mông nhỡ",
  "gluteus minimus": "cơ mông bé",
  gracilis: "cơ thon",
  "gray matter": "chất xám",
  "great cardiac vein": "tĩnh mạch tim lớn",
  "great pancreatic artery": "động mạch tụy lớn",
  "great saphenous vein": "tĩnh mạch hiển lớn",
  gyrus: "hồi",

  // ------------------------------------------------------------- H
  habenula: "cuống tuyến tùng",
  hair: "tóc",
  hairs: "lông tóc",
  hamate: "xương móc",
  hand: "bàn tay",
  "hand proper": "bàn tay (phần chính)",
  head: "đầu",
  "head proper": "đầu (phần chính)",
  heart: "tim",
  "hemiazygos vein": "tĩnh mạch bán đơn",
  hemiliver: "nửa gan",
  "hepatic artery": "động mạch gan",
  "hepatic artery proper": "động mạch gan riêng",
  "hepatic biliary tree": "cây đường mật gan",
  "hepatic duct": "ống gan",
  "hepatic portal vein": "tĩnh mạch cửa gan",
  "hepatic vein": "tĩnh mạch gan",
  "hepatovenous segment ii": "phân thùy tĩnh mạch gan II",
  "hepatovenous segment iii": "phân thùy tĩnh mạch gan III",
  "hepatovenous segment iv": "phân thùy tĩnh mạch gan IV",
  "hepatovenous segment ix": "phân thùy tĩnh mạch gan IX",
  "hepatovenous segment v": "phân thùy tĩnh mạch gan V",
  "hepatovenous segment vi": "phân thùy tĩnh mạch gan VI",
  "hepatovenous segment vii": "phân thùy tĩnh mạch gan VII",
  "hepatovenous segment viii": "phân thùy tĩnh mạch gan VIII",
  "hepatovenous subsector": "phân khu nhỏ tĩnh mạch gan",
  "heterogeneous cluster": "cụm không đồng nhất",
  "heterogeneous clusters": "các cụm không đồng nhất",
  hindbrain: "não sau",
  hip: "hông",
  "hip bone": "xương chậu",
  "hippocampal formation": "thể hải mã",
  hippocampus: "hồi hải mã",
  "hollow tree organ": "cơ quan dạng cây rỗng",
  "human body": "cơ thể người",
  "humeral head": "đầu cánh tay",
  humerus: "xương cánh tay",
  "hyo-epiglottic ligament": "dây chằng móng nắp thanh môn",
  hyoglossus: "cơ móng lưỡi",
  "hyoid bone": "xương móng",
  "hypothalamic branch": "nhánh vùng dưới đồi",
  hypothalamus: "vùng dưới đồi",
  "hypothenar muscle": "cơ mô út",

  // ------------------------------------------------------------- I
  "ileal artery": "động mạch hồi tràng",
  "ileal branch": "nhánh hồi tràng",
  "ileal vein": "tĩnh mạch hồi tràng",
  "ileocecal junction": "chỗ nối hồi manh tràng",
  "ileocolic artery": "động mạch hồi đại tràng",
  "ileocolic vein": "tĩnh mạch hồi đại tràng",
  ileum: "hồi tràng",
  iliacus: "cơ chậu",
  iliococcygeus: "cơ chậu cụt",
  iliocostalis: "cơ chậu sườn",
  "iliocostalis cervicis": "cơ chậu sườn cổ",
  "iliocostalis lumborum": "cơ chậu sườn thắt lưng",
  "iliocostalis thoracis": "cơ chậu sườn ngực",
  "iliolumbar vein": "tĩnh mạch chậu thắt lưng",
  "iliotibial tract": "dải chậu chày",
  "immaterial anatomical entity": "thực thể giải phẫu phi vật chất",
  "incisor tooth": "răng cửa",
  "index finger": "ngón trỏ",
  "inferior basal vein": "tĩnh mạch đáy dưới",
  "inferior branch": "nhánh dưới",
  "inferior colliculus": "gò dưới",
  "inferior division": "ngành dưới",
  "inferior epigastric artery": "động mạch thượng vị dưới",
  "inferior epigastric vein": "tĩnh mạch thượng vị dưới",
  "inferior frontal gyrus": "hồi trán dưới",
  "inferior genicular artery": "động mạch gối dưới",
  "inferior gluteal vein": "tĩnh mạch mông dưới",
  "inferior lateral genicular artery": "động mạch gối dưới ngoài",
  "inferior lingular artery": "động mạch thùy lưỡi dưới",
  "inferior lingular bronchial tree": "cây phế quản thùy lưỡi dưới",
  "inferior lingular bronchopulmonary segment": "phân thùy lưỡi dưới",
  "inferior lingular vein": "tĩnh mạch thùy lưỡi dưới",
  "inferior medial genicular artery": "động mạch gối dưới trong",
  "inferior mediastinum": "trung thất dưới",
  "inferior mesenteric artery": "động mạch mạc treo tràng dưới",
  "inferior mesenteric vein": "tĩnh mạch mạc treo tràng dưới",
  "inferior nasal concha": "xương xoăn mũi dưới",
  "inferior oblique": "cơ chéo dưới",
  "inferior oblique part": "phần chéo dưới",
  "inferior pancreatic artery": "động mạch tụy dưới",
  "inferior pancreaticoduodenal artery": "động mạch tá tụy dưới",
  "inferior part": "phần dưới",
  "inferior pharyngeal constrictor": "cơ khít hầu dưới",
  "inferior phrenic artery": "động mạch hoành dưới",
  "inferior phrenic vein": "tĩnh mạch hoành dưới",
  "inferior pulmonary vein": "tĩnh mạch phổi dưới",
  "inferior rectus": "cơ thẳng dưới",
  "inferior segmental branch": "nhánh phân thùy dưới",
  "inferior segmental renal artery": "động mạch thận phân thùy dưới",
  "inferior suprarenal artery": "động mạch thượng thận dưới",
  "inferior systemic venous tree": "cây tĩnh mạch đại tuần hoàn dưới",
  "inferior temporal gyrus": "hồi thái dương dưới",
  "inferior terminal branch": "nhánh tận dưới",
  "inferior thyroid artery": "động mạch giáp dưới",
  "inferior ulnar collateral artery": "động mạch bên trụ dưới",
  "inferior vena cava": "tĩnh mạch chủ dưới",
  "inferior vena caval tree": "cây tĩnh mạch chủ dưới",
  "inferior wall": "thành dưới",
  "inferomedial branch": "nhánh dưới trong",
  "inferomedial part": "phần dưới trong",
  "inflow part": "phần dòng vào",
  "infrahyoid muscle": "cơ dưới móng",
  infraspinatus: "cơ dưới gai",
  "infraspinatus muscle": "cơ dưới gai",
  "infratrochlear nerve": "thần kinh dưới ròng rọc",
  "innermost intercostal muscle": "cơ gian sườn trong cùng",
  insula: "thùy đảo",
  "insular part": "phần đảo",
  integument: "lớp phủ cơ thể",
  "integumentary system": "hệ da",
  "intercostal muscle": "cơ gian sườn",
  "intermediate cuneiform bone": "xương chêm giữa",
  "intermediate hypothalamic region": "vùng dưới đồi trung gian",
  "intermediate postvertebral muscle": "cơ sau cột sống trung gian",
  "intermediate tendon": "gân trung gian",
  "intermediomedial branch": "nhánh trung gian trong",
  "internal capsule": "bao trong",
  "internal carotid artery": "động mạch cảnh trong",
  "internal gray matter component": "thành phần chất xám bên trong",
  "internal iliac artery": "động mạch chậu trong",
  "internal iliac vein": "tĩnh mạch chậu trong",
  "internal intercostal muscle": "cơ gian sườn trong",
  "internal jugular vein": "tĩnh mạch cảnh trong",
  "internal nose": "mũi trong",
  "internal pudendal artery": "động mạch thẹn trong",
  "internal pudendal vein": "tĩnh mạch thẹn trong",
  "internal thoracic artery": "động mạch ngực trong",
  "internal thoracic vein": "tĩnh mạch ngực trong",
  interosseous: "cơ gian cốt",
  "interosseous membrane": "màng gian cốt",
  "interpeduncular fossa": "hố gian cuống",
  "interspinales cervicis": "cơ gian gai cổ",
  "interspinales lumborum": "cơ gian gai thắt lưng",
  "interspinalis muscle": "cơ gian gai",
  "interspinalis thoracis": "cơ gian gai ngực",
  "intertransversarius muscle": "cơ gian ngang",
  "interventricular foramen": "lỗ gian não thất",
  "intervertebral disk": "đĩa gian đốt sống",
  "intervertebral symphysis": "khớp gian đốt sống",
  "intracranial branch": "nhánh nội sọ",
  "intrahepatic biliary tree": "cây đường mật trong gan",
  "intrapulmonary part": "phần trong phổi",
  "intrapulmonary vein": "tĩnh mạch trong phổi",
  "intrinsic ligament": "dây chằng nội tại",
  "intrinsic muscle": "cơ nội tại",
  "investing fascia": "mạc bọc",
  iris: "mống mắt",
  "irregular bone": "xương không đều",
  "irregular connective tissue": "mô liên kết không đều",

  // ------------------------------------------------------------- J–K
  jejunum: "hỗng tràng",
  kidney: "thận",
  knee: "gối",

  // ------------------------------------------------------------- L
  "lacrimal apparatus": "bộ lệ",
  "lacrimal bone": "xương lệ",
  "lacrimal canaliculus": "tiểu quản lệ",
  "lacrimal duct": "ống lệ",
  "lacrimal gland": "tuyến lệ",
  "lacrimal lake": "hồ lệ",
  "lacrimal nerve": "thần kinh lệ",
  "lacrimal sac": "túi lệ",
  lamina: "lá",
  "lamina terminalis": "lá tận cùng",
  "large intestine": "ruột già",
  "laryngeal cartilage": "sụn thanh quản",
  laryngopharynx: "hầu thanh quản",
  larynx: "thanh quản",
  "lateral basal bronchopulmonary segment": "phân thùy đáy ngoài",
  "lateral basal segmental artery": "động mạch phân thùy đáy ngoài",
  "lateral basal segmental bronchial tree": "cây phế quản phân thùy đáy ngoài",
  "lateral basal segmental vein": "tĩnh mạch phân thùy đáy ngoài",
  "lateral branch": "nhánh ngoài",
  "lateral bronchopulmonary segment": "phân thùy ngoài",
  "lateral chest wall": "thành ngực bên",
  "lateral circumflex femoral artery": "động mạch mũ đùi ngoài",
  "lateral circumflex femoral vein": "tĩnh mạch mũ đùi ngoài",
  "lateral compartment": "khoang ngoài",
  "lateral crico-arytenoid": "cơ nhẫn phễu bên",
  "lateral cuneiform bone": "xương chêm ngoài",
  "lateral frontobasal artery": "động mạch trán nền ngoài",
  "lateral geniculate body": "thể gối ngoài",
  "lateral head": "đầu ngoài",
  "lateral inferior segmental branch": "nhánh phân thùy ngoài dưới",
  "lateral inferior segmental hepatic artery": "động mạch gan phân thùy ngoài dưới",
  "lateral inferior segmental tributary": "nhánh phân thùy ngoài dưới",
  "lateral inferior tributary": "nhánh ngoài dưới",
  "lateral lumbar intertransversarius": "cơ gian ngang thắt lưng ngoài",
  "lateral nasal cartilage": "sụn mũi bên",
  "lateral occipital artery": "động mạch chẩm ngoài",
  "lateral papillary muscle": "cơ nhú ngoài",
  "lateral plantar artery": "động mạch gan chân ngoài",
  "lateral proper palmar digital artery": "động mạch gan ngón tay riêng ngoài",
  "lateral rectus": "cơ thẳng ngoài",
  "lateral sacral vein": "tĩnh mạch cùng bên",
  "lateral segmental artery": "động mạch phân thùy ngoài",
  "lateral segmental bronchial tree": "cây phế quản phân thùy ngoài",
  "lateral segmental hepatic artery": "động mạch gan phân thùy ngoài",
  "lateral segmental vein": "tĩnh mạch phân thùy ngoài",
  "lateral superficial chest wall": "thành ngực nông bên",
  "lateral superior cerebellar artery": "động mạch tiểu não trên ngoài",
  "lateral superior genicular artery": "động mạch gối trên ngoài",
  "lateral superior segmental branch": "nhánh phân thùy ngoài trên",
  "lateral superior segmental hepatic artery": "động mạch gan phân thùy ngoài trên",
  "lateral superior segmental tributary": "nhánh phân thùy ngoài trên",
  "lateral superior tributary": "nhánh ngoài trên",
  "lateral tarsal artery": "động mạch cổ chân ngoài",
  "lateral thoracic artery": "động mạch ngực ngoài",
  "lateral thoracic vein": "tĩnh mạch ngực ngoài",
  "lateral thyrohyoid ligament": "dây chằng giáp móng bên",
  "lateral tributary": "nhánh ngoài",
  "lateral ventricle": "não thất bên",
  "lateral wall": "thành ngoài",
  "laterobasal branch": "nhánh đáy ngoài",
  layer: "lớp",
  leaf: "lá",
  leaflet: "lá van",
  leg: "cẳng chân",
  lens: "thể thủy tinh",
  "levator ani": "cơ nâng hậu môn",
  "levator palpebrae superioris": "cơ nâng mi trên",
  "levator scapulae": "cơ nâng vai",
  "levator veli palatini": "cơ nâng màn khẩu cái",
  "levatores costarum breves": "các cơ nâng sườn ngắn",
  "levatores costarum longi": "các cơ nâng sườn dài",
  ligament: "dây chằng",
  "ligament organ": "dây chằng",
  "ligament organ component": "thành phần dây chằng",
  limb: "chi",
  "limbic lobe": "thùy viền",
  "linea alba": "đường trắng",
  "lingular vein": "tĩnh mạch thùy lưỡi",
  lip: "môi",
  "little finger": "ngón út",
  "little toe": "ngón chân út",
  liver: "gan",
  "liver (in-vivo)": "gan (trong cơ thể sống)",
  "lobar artery": "động mạch thùy",
  lobe: "thùy",
  "lobe branch": "nhánh thùy",
  "lobular organ": "cơ quan có tiểu thùy",
  "lobular organ component": "thành phần cơ quan có tiểu thùy",
  "lobular segment": "đoạn tiểu thùy",
  lobule: "tiểu thùy",
  "long bone": "xương dài",
  "long ciliary nerve": "thần kinh mi dài",
  "long head": "đầu dài",
  "long plantar ligament": "dây chằng gan chân dài",
  longissimus: "cơ dài nhất",
  "longissimus capitis": "cơ dài nhất đầu",
  "longissimus cervicis": "cơ dài nhất cổ",
  "longissimus thoracis": "cơ dài nhất ngực",
  "longus capitis": "cơ dài đầu",
  "longus colli": "cơ dài cổ",
  "loose connective tissue": "mô liên kết thưa",
  "lower central secondary incisor tooth": "răng cửa giữa hàm dưới",
  "lower eyelid": "mí dưới",
  "lower first secondary molar tooth": "răng hàm lớn thứ nhất hàm dưới",
  "lower first secondary premolar tooth": "răng hàm nhỏ thứ nhất hàm dưới",
  "lower gastrointestinal tract": "ống tiêu hoá dưới",
  "lower jaw": "hàm dưới",
  "lower lateral secondary incisor tooth": "răng cửa bên hàm dưới",
  "lower limb": "chi dưới",
  "lower lobar artery": "động mạch thùy dưới",
  "lower lobe": "thùy dưới",
  "lower lobe part": "phần thùy dưới",
  "lower respiratory tract": "đường hô hấp dưới",
  "lower second secondary molar tooth": "răng hàm lớn thứ hai hàm dưới",
  "lower second secondary premolar tooth": "răng hàm nhỏ thứ hai hàm dưới",
  "lower secondary canine tooth": "răng nanh hàm dưới",
  "lower secondary incisor tooth": "răng cửa hàm dưới",
  "lower secondary molar tooth": "răng hàm lớn hàm dưới",
  "lower secondary premolar tooth": "răng hàm nhỏ hàm dưới",
  "lower urinary tract": "đường tiết niệu dưới",
  "lumbar artery": "động mạch thắt lưng",
  "lumbar intertransversarius": "cơ gian ngang thắt lưng",
  "lumbar intervertebral symphysis": "khớp gian đốt sống thắt lưng",
  "lumbar rotator": "cơ xoay thắt lưng",
  "lumbar vein": "tĩnh mạch thắt lưng",
  "lumbar vertebra": "đốt sống thắt lưng",
  "lumbar vertebrae": "các đốt sống thắt lưng",
  "lumbar vertebral column": "cột sống thắt lưng",
  lumbrical: "cơ giun",
  lumbricals: "các cơ giun",
  lunate: "xương nguyệt",
  lung: "phổi",

  // ------------------------------------------------------------- M
  "main bronchus": "phế quản chính",
  "main bronchus proper": "phế quản chính (phần chính)",
  "major alar cartilage": "sụn cánh mũi lớn",
  "major salivary gland": "tuyến nước bọt chính",
  "mammillary body": "thể vú",
  mandible: "xương hàm dưới",
  "mandibular part": "phần hàm dưới",
  manubrium: "cán xương ức",
  "marginal artery": "động mạch bờ",
  "marginal branch": "nhánh bờ",
  "marginal colic artery": "động mạch bờ đại tràng",
  "marginal vein": "tĩnh mạch bờ",
  "material anatomical entity": "thực thể giải phẫu vật chất",
  maxilla: "xương hàm trên",
  "maxillary part": "phần hàm trên",
  "medial basal bronchopulmonary segment": "phân thùy đáy trong",
  "medial basal segmental artery": "động mạch phân thùy đáy trong",
  "medial basal segmental bronchial tree": "cây phế quản phân thùy đáy trong",
  "medial basal segmental vein": "tĩnh mạch phân thùy đáy trong",
  "medial brachial vein": "tĩnh mạch cánh tay trong",
  "medial branch": "nhánh trong",
  "medial bronchopulmonary segment": "phân thùy trong",
  "medial circumflex femoral vein": "tĩnh mạch mũ đùi trong",
  "medial collateral artery": "động mạch bên giữa",
  "medial compartment": "khoang trong",
  "medial cuneiform bone": "xương chêm trong",
  "medial frontobasal artery": "động mạch trán nền trong",
  "medial geniculate body": "thể gối trong",
  "medial head": "đầu trong",
  "medial inferior segmental branch": "nhánh phân thùy trong dưới",
  "medial inferior segmental hepatic artery": "động mạch gan phân thùy trong dưới",
  "medial inferior segmental tributary": "nhánh phân thùy trong dưới",
  "medial inferior tributary": "nhánh trong dưới",
  "medial lumbar intertransversarius": "cơ gian ngang thắt lưng trong",
  "medial occipital artery": "động mạch chẩm trong",
  "medial plantar artery": "động mạch gan chân trong",
  "medial proper palmar digital artery": "động mạch gan ngón tay riêng trong",
  "medial rectus": "cơ thẳng trong",
  "medial segmental artery": "động mạch phân thùy trong",
  "medial segmental bronchial tree": "cây phế quản phân thùy trong",
  "medial segmental hepatic artery": "động mạch gan phân thùy trong",
  "medial segmental vein": "tĩnh mạch phân thùy trong",
  "medial superior genicular artery": "động mạch gối trên trong",
  "medial superior segmental branch": "nhánh phân thùy trong trên",
  "medial superior segmental hepatic artery": "động mạch gan phân thùy trong trên",
  "medial superior segmental tributary": "nhánh phân thùy trong trên",
  "medial superior tributary": "nhánh trong trên",
  "medial tributary": "nhánh trong",
  "median antebrachial vein": "tĩnh mạch giữa cẳng tay",
  "median cricothyroid ligament": "dây chằng nhẫn giáp giữa",
  "median cubital vein": "tĩnh mạch giữa khuỷu",
  "median sacral vein": "tĩnh mạch cùng giữa",
  "median thyrohyoid ligament": "dây chằng giáp móng giữa",
  mediastinum: "trung thất",
  "mediobasal branch": "nhánh đáy trong",
  "medulla oblongata": "hành não",
  "membrane organ": "màng",
  "membrane organ component": "thành phần màng",
  "membranous layer": "lớp màng",
  mesentery: "mạc treo",
  mesoappendix: "mạc treo ruột thừa",
  "metacarpal bone": "xương đốt bàn tay",
  "metatarsal bone": "xương đốt bàn chân",
  metencephalon: "hậu não",
  midbrain: "trung não",
  "midbrain tectum": "mái trung não",
  "middle cardiac vein": "tĩnh mạch tim giữa",
  "middle cerebral artery": "động mạch não giữa",
  "middle colic artery": "động mạch đại tràng giữa",
  "middle colic vein": "tĩnh mạch đại tràng giữa",
  "middle collateral branch": "nhánh bên giữa",
  "middle finger": "ngón giữa",
  "middle frontal gyrus": "hồi trán giữa",
  "middle genicular artery": "động mạch gối giữa",
  "middle hepatic vein": "tĩnh mạch gan giữa",
  "middle lobar artery": "động mạch thùy giữa",
  "middle lobar vein": "tĩnh mạch thùy giữa",
  "middle lobe": "thùy giữa",
  "middle lobe part": "phần thùy giữa",
  "middle mediastinum": "trung thất giữa",
  "middle part": "phần giữa",
  "middle phalanx": "đốt giữa",
  "middle pharyngeal constrictor": "cơ khít hầu giữa",
  "middle suprarenal artery": "động mạch thượng thận giữa",
  "middle temporal branch": "nhánh thái dương giữa",
  "middle temporal gyrus": "hồi thái dương giữa",
  "mitral valve": "van hai lá",
  "molar tooth": "răng hàm lớn",
  "mons pubis": "gò mu",
  mouth: "miệng",
  "mucoid tissue": "mô nhầy",
  muscle: "cơ",
  "muscle layer": "lớp cơ",
  "muscle organ": "cơ",
  musculature: "hệ cơ",
  "musculophrenic artery": "động mạch cơ hoành",
  "musculophrenic vein": "tĩnh mạch cơ hoành",
  "musculoskeletal system": "hệ cơ xương",
  mylohyoid: "cơ hàm móng",
  "myocardial zone 11": "vùng cơ tim 11",
  "myocardial zone 12": "vùng cơ tim 12",
  "myocardial zone 4": "vùng cơ tim 4",
  myocardium: "cơ tim",

  // ------------------------------------------------------------- N
  "nasal bone": "xương mũi",
  "nasal cartilage": "sụn mũi",
  "nasal septum": "vách mũi",
  "nasal skeleton": "khung mũi",
  "nasociliary nerve": "thần kinh mũi mi",
  "nasolacrimal duct": "ống lệ mũi",
  "navicular bone": "xương ghe",
  neck: "cổ",
  nerve: "thần kinh",
  "nerve trunk": "thân thần kinh",
  "nervous system": "hệ thần kinh",
  "neural tree organ": "cây thần kinh",
  neuraxis: "trục thần kinh",
  neurocranium: "sọ não",
  "nonparenchymatous organ": "cơ quan không nhu mô",
  "nonskeletal ligament": "dây chằng không thuộc xương",
  nose: "mũi",
  "nuclear complex": "phức hợp nhân",
  nucleus: "nhân",

  // ------------------------------------------------------------- O
  "oblique arytenoid": "cơ phễu chéo",
  "oblique head": "đầu chéo",
  "oblique part": "phần chéo",
  "obliquus capitis inferior": "cơ chéo đầu dưới",
  "obliquus capitis superior": "cơ chéo đầu trên",
  "obturator externus": "cơ bịt ngoài",
  "obturator internus": "cơ bịt trong",
  "obturator muscle": "cơ bịt",
  "obturator vein": "tĩnh mạch bịt",
  "occipital bone": "xương chẩm",
  "occipital lobe": "thùy chẩm",
  "occipital part": "phần chẩm",
  "oculomotor nerve": "thần kinh vận nhãn",
  "oesophageal branches": "các nhánh thực quản",
  omohyoid: "cơ vai móng",
  "ophthalmic artery": "động mạch mắt",
  "ophthalmic nerve": "thần kinh mắt",
  "opponens digiti minimi": "cơ đối ngón út",
  "opponens pollicis": "cơ đối ngón cái",
  "optic chiasm": "giao thoa thị giác",
  "optic nerve": "thần kinh thị giác",
  "optic part": "phần thị giác",
  "optic tract": "dải thị giác",
  orbit: "ổ mắt",
  "orbital compartment": "khoang ổ mắt",
  "orbital content": "thành phần ổ mắt",
  "orbital gyrus": "hồi ổ mắt",
  "orbital part": "phần ổ mắt",
  organ: "cơ quan",
  "organ cavity": "khoang cơ quan",
  "organ cavity subdivision": "phân vùng khoang cơ quan",
  "organ chamber": "buồng cơ quan",
  "organ component": "thành phần cơ quan",
  "organ component cluster": "cụm thành phần cơ quan",
  "organ component gland": "tuyến thành phần cơ quan",
  "organ component layer": "lớp thành phần cơ quan",
  "organ part": "phần cơ quan",
  "organ part cluster": "cụm phần cơ quan",
  "organ parts": "các phần cơ quan",
  "organ region": "vùng cơ quan",
  "organ regions": "các vùng cơ quan",
  "organ segment": "đoạn cơ quan",
  "organ zone": "vùng cơ quan",
  organs: "các cơ quan",
  "osseous skeleton": "bộ xương",
  "outflow part": "phần dòng ra",

  // ------------------------------------------------------------- P
  palate: "khẩu cái",
  "palatine bone": "xương khẩu cái",
  palatopharyngeus: "cơ khẩu cái hầu",
  "palmar interossei": "các cơ gian cốt gan tay",
  "palmar metacarpal artery": "động mạch gan đốt bàn tay",
  "palmar metacarpal vein": "tĩnh mạch gan đốt bàn tay",
  "palmaris longus": "cơ gan tay dài",
  pancreas: "tụy",
  "pancreatic artery": "động mạch tụy",
  "pancreatic duct": "ống tụy",
  "pancreatic duct tree": "cây ống tụy",
  "pancreaticobiliary system": "hệ tụy mật",
  "pancreaticoduodenal vein": "tĩnh mạch tá tụy",
  "papillary muscle": "cơ nhú",
  "paracentral branch": "nhánh cạnh trung tâm",
  "parahippocampal gyrus": "hồi cạnh hải mã",
  "parasympathetic ganglion": "hạch đối giao cảm",
  "parasympathetic nervous system": "hệ thần kinh đối giao cảm",
  parenchyma: "nhu mô",
  "parenchymatous organ": "cơ quan nhu mô",
  "parietal bone": "xương đỉnh",
  "parietal lobe": "thùy đỉnh",
  "parietal part": "phần đỉnh",
  patella: "xương bánh chè",
  "patellar part": "phần bánh chè",
  pectineus: "cơ lược",
  "pectoral branch": "nhánh ngực",
  "pectoral girdle": "đai ngực",
  "pectoral muscle": "cơ ngực",
  "pectoral part": "phần ngực",
  "pectoralis major": "cơ ngực lớn",
  "pectoralis minor": "cơ ngực bé",
  peduncle: "cuống",
  "pelvic girdle": "đai chậu",
  "pelvic skeleton": "khung xương chậu",
  "pelvic wall": "thành chậu",
  pelvis: "chậu hông",
  penis: "dương vật",
  "perforating arteries": "các động mạch xuyên",
  "perforating veins": "các tĩnh mạch xuyên",
  "pericallosal artery": "động mạch quanh thể chai",
  "perineal muscle": "cơ đáy chậu",
  perineum: "đáy chậu",
  "peritoneal mesentery": "mạc treo phúc mạc",
  "peritoneal sac": "túi phúc mạc",
  peritoneum: "phúc mạc",
  phalanx: "đốt ngón",
  "pharyngeal raphe": "đường đan hầu",
  pharynx: "hầu",
  "physical anatomical entity": "thực thể giải phẫu vật lý",
  "pineal body": "tuyến tùng",
  piriformis: "cơ hình lê",
  pisiform: "xương đậu",
  "pituitary gland": "tuyến yên",
  "plantar arch": "cung gan chân",
  "plantar digital arteries proper": "các động mạch gan ngón chân riêng",
  "plantar digital veins": "các tĩnh mạch gan ngón chân",
  "plantar interosseous": "cơ gian cốt gan chân",
  "plantar metatarsal artery": "động mạch gan đốt bàn chân",
  "plantar metatarsal vein": "tĩnh mạch gan đốt bàn chân",
  "plantar part": "phần gan chân",
  "plantar tarsal ligament": "dây chằng gan cổ chân",
  "plantar venous arch": "cung tĩnh mạch gan chân",
  plantaris: "cơ gan chân",
  platysma: "cơ bám da cổ",
  "pneumatized bone": "xương có xoang khí",
  "polar temporal artery": "động mạch cực thái dương",
  pons: "cầu não",
  "pontine artery": "động mạch cầu não",
  "popliteal artery": "động mạch khoeo",
  "popliteal vein": "tĩnh mạch khoeo",
  popliteus: "cơ khoeo",
  "portal vein": "tĩnh mạch cửa",
  "portal venous system": "hệ tĩnh mạch cửa",
  "portal venous tree": "cây tĩnh mạch cửa",
  portion: "phần",
  "postcentral gyrus": "hồi sau trung tâm",
  "postcentral sulcus": "rãnh sau trung tâm",
  "postcommunicating part": "phần sau thông",
  "posterior abdominal wall": "thành bụng sau",
  "posterior basal bronchopulmonary segment": "phân thùy đáy sau",
  "posterior basal segmental artery": "động mạch phân thùy đáy sau",
  "posterior basal segmental bronchial tree": "cây phế quản phân thùy đáy sau",
  "posterior basal segmental vein": "tĩnh mạch phân thùy đáy sau",
  "posterior branch": "nhánh sau",
  "posterior bronchopulmonary segment": "phân thùy sau",
  "posterior cecal artery": "động mạch manh tràng sau",
  "posterior cerebral artery": "động mạch não sau",
  "posterior cervical intertransversarii": "các cơ gian ngang cổ sau",
  "posterior chest": "ngực sau",
  "posterior choroidal artery": "động mạch mạch mạc sau",
  "posterior circumflex humeral artery": "động mạch mũ cánh tay sau",
  "posterior commissure": "mép sau",
  "posterior communicating artery": "động mạch thông sau",
  "posterior compartment": "khoang sau",
  "posterior crico-arytenoid": "cơ nhẫn phễu sau",
  "posterior cusp": "lá van sau",
  "posterior division": "ngành sau",
  "posterior ethmoidal nerve": "thần kinh sàng sau",
  "posterior inferior cerebellar artery": "động mạch tiểu não sau dưới",
  "posterior inferior pancreaticoduodenal artery": "động mạch tá tụy dưới sau",
  "posterior inferior segmental branch": "nhánh phân thùy sau dưới",
  "posterior inferior segmental hepatic artery": "động mạch gan phân thùy sau dưới",
  "posterior inferior segmental tributary": "nhánh phân thùy sau dưới",
  "posterior inferior tributary": "nhánh sau dưới",
  "posterior intercostal arteries": "các động mạch gian sườn sau",
  "posterior intercostal artery": "động mạch gian sườn sau",
  "posterior interventricular artery": "động mạch gian thất sau",
  "posterior interventricular branch": "nhánh gian thất sau",
  "posterior leaflet": "lá van sau",
  "posterior limb": "trụ sau",
  "posterior medial choroidal artery": "động mạch mạch mạc sau trong",
  "posterior mediastinum": "trung thất sau",
  "posterior papillary muscle": "cơ nhú sau",
  "posterior parietal artery": "động mạch đỉnh sau",
  "posterior part": "phần sau",
  "posterior sector": "phân khu sau",
  "posterior segmental artery": "động mạch phân thùy sau",
  "posterior segmental branch": "nhánh phân thùy sau",
  "posterior segmental bronchial tree": "cây phế quản phân thùy sau",
  "posterior segmental hepatic artery": "động mạch gan phân thùy sau",
  "posterior segmental renal artery": "động mạch thận phân thùy sau",
  "posterior segmental vein": "tĩnh mạch phân thùy sau",
  "posterior suboccipital muscle": "cơ dưới chẩm sau",
  "posterior superior pancreaticoduodenal artery": "động mạch tá tụy trên sau",
  "posterior superior segmental branch": "nhánh phân thùy sau trên",
  "posterior superior segmental hepatic artery": "động mạch gan phân thùy sau trên",
  "posterior superior segmental tributary": "nhánh phân thùy sau trên",
  "posterior superior tributary": "nhánh sau trên",
  "posterior temporal branch": "nhánh thái dương sau",
  "posterior temporal branches": "các nhánh thái dương sau",
  "posterior thoracic wall": "thành ngực sau",
  "posterior tibial artery": "động mạch chày sau",
  "posterior tibial vein": "tĩnh mạch chày sau",
  "posterior tributary": "nhánh sau",
  "posterior ulnar recurrent artery": "động mạch quặt ngược trụ sau",
  "posterior vein": "tĩnh mạch sau",
  "posterior ventricular branch": "nhánh thất sau",
  "posteromedial branch": "nhánh sau trong",
  "posteromedial central branch": "nhánh trung tâm sau trong",
  "postvertebral muscle": "cơ sau cột sống",
  "pre-hepatic portal vein": "tĩnh mạch cửa trước gan",
  "precentral gyrus": "hồi trước trung tâm",
  "precentral sulcus": "rãnh trước trung tâm",
  "precommunicating part": "phần trước thông",
  "precuneal branch": "nhánh tiền chêm",
  "prefrontal artery": "động mạch trước trán",
  "prefrontal cortex": "vỏ não trước trán",
  "premolar tooth": "răng hàm nhỏ",
  "prevertebral muscle": "cơ trước cột sống",
  process: "mỏm",
  "pronator quadratus": "cơ sấp vuông",
  "pronator teres": "cơ sấp tròn",
  "proper palmar digital vein": "tĩnh mạch gan ngón tay riêng",
  prostate: "tuyến tiền liệt",
  "proximal carpal bone": "xương cổ tay hàng gần",
  "proximal part": "phần gần",
  "proximal phalanx": "đốt gần",
  "psoas major": "cơ thắt lưng lớn",
  "pterygomandibular raphe": "đường đan chân bướm hàm",
  "pubic hair": "lông mu",
  pubococcygeus: "cơ mu cụt",
  puborectalis: "cơ mu trực tràng",
  "pulmonary arterial tree": "cây động mạch phổi",
  "pulmonary arterial trunk": "thân động mạch phổi",
  "pulmonary artery": "động mạch phổi",
  "pulmonary segment": "phân thùy phổi",
  "pulmonary trunk": "thân động mạch phổi",
  "pulmonary valve": "van động mạch phổi",
  "pulmonary vascular system": "hệ mạch phổi",
  "pulmonary vein": "tĩnh mạch phổi",
  "pulmonary venous tree organ": "cây tĩnh mạch phổi",
  "pulmopleural compartment": "khoang phổi màng phổi",
  putamen: "nhân bèo",

  // ------------------------------------------------------------- Q–R
  "quadratus femoris": "cơ vuông đùi",
  "quadriceps femoris": "cơ tứ đầu đùi",
  "radial artery": "động mạch quay",
  "radial collateral artery": "động mạch bên quay",
  "radial collateral branch": "nhánh bên quay",
  "radial recurrent artery": "động mạch quặt ngược quay",
  "radial vein": "tĩnh mạch quay",
  radius: "xương quay",
  rectum: "trực tràng",
  "rectus capitis anterior": "cơ thẳng đầu trước",
  "rectus capitis lateralis": "cơ thẳng đầu ngoài",
  "rectus capitis posterior major": "cơ thẳng đầu sau lớn",
  "rectus capitis posterior minor": "cơ thẳng đầu sau bé",
  "rectus femoris": "cơ thẳng đùi",
  "recurrent interosseous artery": "động mạch gian cốt quặt ngược",
  region: "vùng",
  "renal artery": "động mạch thận",
  "renal vein": "tĩnh mạch thận",
  "respiratory system": "hệ hô hấp",
  "respiratory tract": "đường hô hấp",
  retina: "võng mạc",
  retinaculum: "mạc hãm",
  "rhomboid major": "cơ trám lớn",
  "rhomboid minor": "cơ trám bé",
  rib: "xương sườn",
  "rib cage": "lồng ngực",
  "ring finger": "ngón nhẫn",
  root: "rễ",
  "rotator muscle": "cơ xoay",

  // ------------------------------------------------------------- S
  sacrum: "xương cùng",
  "salivary gland": "tuyến nước bọt",
  salpingopharyngeus: "cơ vòi hầu",
  sartorius: "cơ may",
  "scalene muscle": "cơ bậc thang",
  "scalenus anterior": "cơ bậc thang trước",
  "scalenus medius": "cơ bậc thang giữa",
  "scalenus posterior": "cơ bậc thang sau",
  scaphoid: "xương thuyền",
  scapula: "xương vai",
  "scapular part": "phần vai",
  sclera: "củng mạc",
  "secondary canine tooth": "răng nanh vĩnh viễn",
  "secondary incisor tooth": "răng cửa vĩnh viễn",
  "secondary molar tooth": "răng hàm lớn vĩnh viễn",
  segment: "phân đoạn",
  "segmental pulmonary artery": "động mạch phổi phân thùy",
  "segmental pulmonary vein": "tĩnh mạch phổi phân thùy",
  "segmental renal artery": "động mạch thận phân thùy",
  "segmental tributary": "nhánh phân thùy",
  semimembranosus: "cơ bán màng",
  "seminal vesicle": "túi tinh",
  semispinalis: "cơ bán gai",
  "semispinalis capitis": "cơ bán gai đầu",
  "semispinalis cervicis": "cơ bán gai cổ",
  "semispinalis thoracis": "cơ bán gai ngực",
  semitendinosus: "cơ bán gân",
  "septal branch": "nhánh vách",
  "septal leaflet": "lá van vách",
  "septal nasal cartilage": "sụn vách mũi",
  "septal papillary muscle": "cơ nhú vách",
  septum: "vách",
  "serous membrane": "thanh mạc",
  "serratus anterior": "cơ răng trước",
  "serratus posterior": "cơ răng sau",
  "serratus posterior inferior": "cơ răng sau dưới",
  "serratus posterior superior": "cơ răng sau trên",
  "sesamoid bone": "xương vừng",
  set: "nhóm",
  "short bone": "xương ngắn",
  "short ciliary nerve": "thần kinh mi ngắn",
  "short head": "đầu ngắn",
  shoulder: "vai",
  side: "bên",
  "sigmoid artery": "động mạch sigma",
  "sigmoid vein": "tĩnh mạch sigma",
  "skeletal ligament": "dây chằng xương",
  "skeletal system": "hệ xương",
  skeleton: "bộ xương",
  "skeleton (in vivo)": "bộ xương (trong cơ thể sống)",
  skin: "da",
  "skin appendage": "phần phụ của da",
  skull: "hộp sọ",
  "small cardiac vein": "tĩnh mạch tim nhỏ",
  "small intestine": "ruột non",
  "small saphenous vein": "tĩnh mạch hiển bé",
  "soft palate": "khẩu cái mềm",
  soleus: "cơ dép",
  "solid organ": "cơ quan đặc",
  space: "khoang",
  "sphenoid bone": "xương bướm",
  "sphenoid part": "phần bướm",
  "spinal cord": "tủy sống",
  "spinal part": "phần gai",
  spinalis: "cơ gai",
  "spinalis thoracis": "cơ gai ngực",
  spleen: "lách",
  "splenial artery": "động mạch lồi thể chai",
  "splenic artery": "động mạch lách",
  "splenic vein": "tĩnh mạch lách",
  splenius: "cơ gối",
  "splenius capitis": "cơ gối đầu",
  "splenius cervicis": "cơ gối cổ",
  "sternal part": "phần ức",
  sternocleidomastoid: "cơ ức đòn chũm",
  "sternocostal part": "phần ức sườn",
  sternohyoid: "cơ ức móng",
  sternothyroid: "cơ ức giáp",
  sternum: "xương ức",
  stomach: "dạ dày",
  "straight part": "phần thẳng",
  stria: "vân",
  "stria medullaris": "vân tủy",
  "stria terminalis": "vân tận cùng",
  stylohyoid: "cơ trâm móng",
  "stylohyoid ligament": "dây chằng trâm móng",
  stylopharyngeus: "cơ trâm hầu",
  "subaortic curtain": "màn dưới động mạch chủ",
  "subarachnoid incisure": "khuyết dưới nhện",
  "subarachnoid space": "khoang dưới nhện",
  "subclavian artery": "động mạch dưới đòn",
  "subclavian vein": "tĩnh mạch dưới đòn",
  subclavius: "cơ dưới đòn",
  subcortex: "vùng dưới vỏ",
  "subcostal artery": "động mạch dưới sườn",
  "subcostal vein": "tĩnh mạch dưới sườn",
  subdivision: "phân vùng",
  "subdivisionof autonomic nervous system": "phân vùng hệ thần kinh tự chủ",
  "subendocardial layer": "lớp dưới nội tâm mạc",
  "sublingual gland": "tuyến dưới lưỡi",
  "submandibular gland": "tuyến dưới hàm",
  "subscapular artery": "động mạch dưới vai",
  "subscapular vein": "tĩnh mạch dưới vai",
  subscapularis: "cơ dưới vai",
  "subsegmental part": "phần hạ phân thùy",
  "subsegmental pulmonary artery": "động mạch phổi hạ phân thùy",
  "subsegmental pulmonary vein": "tĩnh mạch phổi hạ phân thùy",
  "superficial cervical artery": "động mạch cổ nông",
  "superficial chest wall": "thành ngực nông",
  "superficial dorsal vein": "tĩnh mạch mu nông",
  "superficial epigastric artery": "động mạch thượng vị nông",
  "superficial epigastric vein": "tĩnh mạch thượng vị nông",
  "superficial external pudendal vein": "tĩnh mạch thẹn ngoài nông",
  "superficial head": "đầu nông",
  "superficial medial plantar artery": "động mạch gan chân trong nông",
  "superficial muscle": "cơ nông",
  "superficial palmar arterial arch": "cung động mạch gan tay nông",
  "superficial palmar venous arch": "cung tĩnh mạch gan tay nông",
  "superficial perineal muscle": "cơ đáy chậu nông",
  "superficial postvertebral muscle": "cơ sau cột sống nông",
  "superior basal vein": "tĩnh mạch đáy trên",
  "superior branch": "nhánh trên",
  "superior bronchopulmonary segment": "phân thùy trên",
  "superior cerebellar artery": "động mạch tiểu não trên",
  "superior colliculus": "gò trên",
  "superior division": "ngành trên",
  "superior epigastric artery": "động mạch thượng vị trên",
  "superior epigastric vein": "tĩnh mạch thượng vị trên",
  "superior frontal gyrus": "hồi trán trên",
  "superior genicular artery": "động mạch gối trên",
  "superior gluteal vein": "tĩnh mạch mông trên",
  "superior intercostal artery": "động mạch gian sườn trên",
  "superior intercostal vein": "tĩnh mạch gian sườn trên",
  "superior lateral genicular artery": "động mạch gối trên ngoài",
  "superior lingular artery": "động mạch thùy lưỡi trên",
  "superior lingular bronchial tree": "cây phế quản thùy lưỡi trên",
  "superior lingular bronchopulmonary segment": "phân thùy lưỡi trên",
  "superior lingular vein": "tĩnh mạch thùy lưỡi trên",
  "superior medial genicular artery": "động mạch gối trên trong",
  "superior mediastinum": "trung thất trên",
  "superior mesenteric artery": "động mạch mạc treo tràng trên",
  "superior mesenteric vein": "tĩnh mạch mạc treo tràng trên",
  "superior oblique": "cơ chéo trên",
  "superior oblique part": "phần chéo trên",
  "superior pancreaticoduodenal artery": "động mạch tá tụy trên",
  "superior parietal lobule": "tiểu thùy đỉnh trên",
  "superior part": "phần trên",
  "superior pharyngeal constrictor": "cơ khít hầu trên",
  "superior phrenic vein": "tĩnh mạch hoành trên",
  "superior pulmonary vein": "tĩnh mạch phổi trên",
  "superior rectal artery": "động mạch trực tràng trên",
  "superior rectal vein": "tĩnh mạch trực tràng trên",
  "superior rectus": "cơ thẳng trên",
  "superior segmental artery": "động mạch phân thùy trên",
  "superior segmental branch": "nhánh phân thùy trên",
  "superior segmental bronchial tree": "cây phế quản phân thùy trên",
  "superior segmental renal artery": "động mạch thận phân thùy trên",
  "superior segmental vein": "tĩnh mạch phân thùy trên",
  "superior systemic venous tree": "cây tĩnh mạch đại tuần hoàn trên",
  "superior temporal gyrus": "hồi thái dương trên",
  "superior terminal branch": "nhánh tận trên",
  "superior ulnar collateral artery": "động mạch bên trụ trên",
  "superior vena cava": "tĩnh mạch chủ trên",
  "superior vena caval tree": "cây tĩnh mạch chủ trên",
  "superior vermian branch": "nhánh thùy nhộng trên",
  supinator: "cơ ngửa",
  "supra-orbital nerve": "thần kinh trên ổ mắt",
  "suprahyoid muscle": "cơ trên móng",
  "supramarginal gyrus": "hồi trên viền",
  "suprarenal vein": "tĩnh mạch thượng thận",
  "suprascapular artery": "động mạch trên vai",
  "suprascapular vein": "tĩnh mạch trên vai",
  supraspinatus: "cơ trên gai",
  "supratrochlear nerve": "thần kinh trên ròng rọc",
  "supreme intercostal artery": "động mạch gian sườn cao nhất",
  "suspensory ligament": "dây chằng treo",
  symphysis: "khớp dính",
  "systemic arterial system": "hệ động mạch đại tuần hoàn",
  "systemic arterial tree": "cây động mạch đại tuần hoàn",
  "systemic arterial trunk": "thân động mạch đại tuần hoàn",
  "systemic artery": "động mạch đại tuần hoàn",
  "systemic vein": "tĩnh mạch đại tuần hoàn",
  "systemic venous system": "hệ tĩnh mạch đại tuần hoàn",

  // ------------------------------------------------------------- T
  "taenia coli": "dải cơ dọc đại tràng",
  "taenia libera": "dải tự do",
  "taenia mesocolica": "dải mạc treo",
  "taenia omentalis": "dải mạc nối",
  talus: "xương sên",
  "tarsal bone": "xương cổ chân",
  "tarsal ligament": "dây chằng cổ chân",
  "tarsal plate": "sụn mi",
  telencephalon: "đoan não",
  "temporal artery": "động mạch thái dương",
  "temporal bone": "xương thái dương",
  "temporal lobe": "thùy thái dương",
  "temporo-occipital branch": "nhánh thái dương chẩm",
  "tendinous arch": "cung gân",
  tendon: "gân",
  "tensor fasciae latae": "cơ căng mạc đùi",
  "tensor veli palatini": "cơ căng màn khẩu cái",
  "tentorium cerebelli": "lều tiểu não",
  "teres major": "cơ tròn lớn",
  "teres minor": "cơ tròn bé",
  "testicular artery": "động mạch tinh hoàn",
  "testicular vein": "tĩnh mạch tinh hoàn",
  testis: "tinh hoàn",
  "thalamogeniculate artery": "động mạch đồi thị gối",
  "thalamoperforating artery": "động mạch xuyên đồi thị",
  thalamus: "đồi thị",
  "thenar muscle": "cơ mô cái",
  thigh: "đùi",
  "third ventricle": "não thất ba",
  "thoracic aorta": "động mạch chủ ngực",
  "thoracic intervertebral symphysis": "khớp gian đốt sống ngực",
  "thoracic part": "phần ngực",
  "thoracic rotator": "cơ xoay ngực",
  "thoracic segment": "đoạn ngực",
  "thoracic vertebra": "đốt sống ngực",
  "thoracic vertebrae": "các đốt sống ngực",
  "thoracic vertebral column": "cột sống ngực",
  "thoracic wall": "thành ngực",
  "thoraco-acromial artery": "động mạch ngực cùng vai",
  "thoracodorsal artery": "động mạch ngực lưng",
  "thoracodorsal vein": "tĩnh mạch ngực lưng",
  thorax: "ngực",
  thumb: "ngón cái",
  thymus: "tuyến ức",
  "thyro-arytenoid": "cơ giáp phễu",
  "thyro-epiglottic ligament": "dây chằng giáp nắp thanh môn",
  "thyrocervical artery": "động mạch giáp cổ",
  "thyrocervical trunk": "thân giáp cổ",
  thyrohyoid: "cơ giáp móng",
  "thyrohyoid ligament": "dây chằng giáp móng",
  "thyrohyoid membrane": "màng giáp móng",
  "thyroid cartilage": "sụn giáp",
  tibia: "xương chày",
  "tibialis anterior": "cơ chày trước",
  "tibialis posterior": "cơ chày sau",
  tissue: "mô",
  toe: "ngón chân",
  tongue: "lưỡi",
  tooth: "răng",
  trachea: "khí quản",
  "tracheobronchial tree": "cây khí phế quản",
  "transverse arytenoid": "cơ phễu ngang",
  "transverse cervical artery": "động mạch cổ ngang",
  "transverse colon": "đại tràng ngang",
  "transverse head": "đầu ngang",
  "transverse mesocolon": "mạc treo đại tràng ngang",
  "transverse part": "phần ngang",
  "transversus thoracis": "cơ ngang ngực",
  trapezium: "xương thang",
  trapezius: "cơ thang",
  trapezoid: "xương thê",
  tributary: "nhánh",
  "triceps brachii": "cơ tam đầu cánh tay",
  "tricuspid valve": "van ba lá",
  "trigeminal nerve": "thần kinh sinh ba",
  triquetral: "xương tháp",
  trochlea: "ròng rọc",
  "trochlear nerve": "thần kinh ròng rọc",
  "true rib": "xương sườn thật",
  trunk: "thân",
  "tuber cinereum": "củ xám",
  "typical rib": "xương sườn điển hình",

  // ------------------------------------------------------------- U
  ulna: "xương trụ",
  "ulnar artery": "động mạch trụ",
  "ulnar head": "đầu trụ",
  "ulnar recurrent artery": "động mạch quặt ngược trụ",
  "ulnar vein": "tĩnh mạch trụ",
  "upper central secondary incisor tooth": "răng cửa giữa hàm trên",
  "upper eyelid": "mí trên",
  "upper first secondary molar tooth": "răng hàm lớn thứ nhất hàm trên",
  "upper first secondary premolar tooth": "răng hàm nhỏ thứ nhất hàm trên",
  "upper gastrointestinal tract": "ống tiêu hoá trên",
  "upper jaw": "hàm trên",
  "upper lateral secondary incisor tooth": "răng cửa bên hàm trên",
  "upper limb": "chi trên",
  "upper lobar artery": "động mạch thùy trên",
  "upper lobar vein": "tĩnh mạch thùy trên",
  "upper lobe": "thùy trên",
  "upper lobe part": "phần thùy trên",
  "upper second secondary molar tooth": "răng hàm lớn thứ hai hàm trên",
  "upper second secondary premolar tooth": "răng hàm nhỏ thứ hai hàm trên",
  "upper secondary canine tooth": "răng nanh hàm trên",
  "upper secondary incisor tooth": "răng cửa hàm trên",
  "upper secondary molar tooth": "răng hàm lớn hàm trên",
  "upper secondary premolar tooth": "răng hàm nhỏ hàm trên",
  "upper urinary tract": "đường tiết niệu trên",
  ureter: "niệu quản",
  "ureteric segment": "đoạn niệu quản",
  urethra: "niệu đạo",
  "urinary bladder": "bàng quang",
  "urinary system": "hệ tiết niệu",
  uvula: "lưỡi gà",
  "uvular muscle": "cơ lưỡi gà",

  // ------------------------------------------------------------- V–Z
  "variant artery": "động mạch biến thể",
  "variant bronchial artery": "động mạch phế quản biến thể",
  "variant systemic artery": "động mạch đại tuần hoàn biến thể",
  "vascular anastomosis": "nhánh nối mạch máu",
  "vascular layer": "lớp mạch",
  "vascular tree": "cây mạch máu",
  "vascular tree organ": "cây mạch máu",
  vasculature: "hệ mạch",
  "vastus intermedius": "cơ rộng giữa",
  "vastus lateralis": "cơ rộng ngoài",
  "vastus medialis": "cơ rộng trong",
  vein: "tĩnh mạch",
  veins: "các tĩnh mạch",
  "venous anastomosis": "nhánh nối tĩnh mạch",
  "venous tree organ": "cây tĩnh mạch",
  "venous trunk": "thân tĩnh mạch",
  ventricle: "tâm thất",
  "ventricle proper": "tâm thất (phần chính)",
  "ventricular branch": "nhánh thất",
  "ventricular system": "hệ não thất",
  vertebra: "đốt sống",
  "vertebral artery": "động mạch đốt sống",
  "vertebral column": "cột sống",
  "vertical intermediate part": "phần trung gian đứng",
  "visceral peritoneum": "phúc mạc tạng",
  viscerocranium: "sọ mặt",
  "vitreous body": "thể kính",
  "vocal ligament": "dây chằng thanh âm",
  vocalis: "cơ thanh âm",
  vomer: "xương lá mía",
  wall: "thành",
  "white matter": "chất trắng",
  wrist: "cổ tay",
  "xiphoid process": "mỏm mũi kiếm",
  zone: "vùng",
  "zygomatic bone": "xương gò má",
};

/** Cả tên ghép mà ghép từng cụm ra sai nghĩa — tra trước khi tách. */
const WHOLE: Record<string, string> = {
  "dorsum of nose": "sống mũi",
};

const ORDINALS: Record<string, number> = {
  first: 1,
  second: 2,
  third: 3,
  fourth: 4,
  fifth: 5,
  sixth: 6,
  seventh: 7,
  eighth: 8,
  ninth: 9,
  tenth: 10,
  eleventh: 11,
  twelfth: 12,
};

const SIDE: Record<string, string> = { left: "trái", right: "phải" };
const JOIN: Record<string, string> = { of: " ", to: " tới ", with: " với " };

/** Một cụm không chứa "of/to/with": tra thẳng, hoặc "<số thứ tự> <cụm>" → "<cụm> <số>". */
function atom(text: string): string | null {
  const direct = T[text];
  if (direct) return direct;
  const [first, ...rest] = text.split(" ");
  const n = ORDINALS[first];
  if (n && rest.length > 0) {
    const base = T[rest.join(" ")];
    if (base) return `${base} ${n}`;
  }
  return null;
}

/**
 * "Left external oblique" → "cơ chéo bụng ngoài trái";
 * "distal phalanx of right thumb" → "đốt xa ngón cái phải".
 * Có cụm nào chưa dịch thì trả `null` để bên gọi dùng tên gốc.
 */
export function translateAnatomy(english: string): string | null {
  const name = english.toLowerCase().replace(/\s+/g, " ").trim();
  const whole = WHOLE[name];
  if (whole) return whole;

  const pieces = name.split(/ (of|to|with) /);
  let out = "";
  for (let i = 0; i < pieces.length; i += 2) {
    let side = "";
    const text = pieces[i]
      .replace(/\b(left|right)\b/g, (m) => {
        side = SIDE[m];
        return "";
      })
      .replace(/\s+/g, " ")
      .trim();
    const vi = atom(text);
    if (!vi) return null;
    if (i > 0) out += JOIN[pieces[i - 1]];
    // Trái/phải đứng ngay sau cụm nó bổ nghĩa: "right lobe of thymus" →
    // "thùy phải tuyến ức" (thùy là bên phải, không phải tuyến ức), và trước
    // phần chú thích trong ngoặc: "gan phải (trong cơ thể sống)".
    const paren = vi.indexOf(" (");
    out += !side ? vi : paren < 0 ? `${vi} ${side}` : `${vi.slice(0, paren)} ${side}${vi.slice(paren)}`;
  }
  return out;
}
