import type { Metadata } from "next";
import { getTranslations, setRequestLocale } from "next-intl/server";

import type { Locale } from "@/i18n/routing";
import { buildMetadata } from "@/lib/seo";
import { StaticPage } from "@/components/static-page";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "footer" });

  return buildMetadata({
    title: t("terms"),
    description: t("terms"),
    path: "/terms",
    locale: locale as Locale,
  });
}

export default async function TermsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  const t = await getTranslations("footer");
  const en = locale === "en";

  return (
    <StaticPage title={t("terms")} updatedAt="01/09/2026">
      {en ? (
        <>
          <h2>Using the content</h2>
          <p>
            Articles on Sciencepedia are published under CC BY-SA 4.0. You may
            copy, adapt and redistribute them, including commercially, provided
            you credit Sciencepedia and share derivatives under the same licence.
          </p>

          <h2>Contributing</h2>
          <p>
            Contributors keep authorship credit but grant Sciencepedia the right
            to publish, edit and redistribute their contributions under the same
            licence. Do not submit material you do not have the right to publish.
          </p>

          <h2>The AI assistant</h2>
          <p>
            Answers are generated by a language model and may be incomplete or
            wrong. Always check the cited articles. Health information on this
            site is for reference only and is not medical advice.
          </p>

          <h2>Accounts</h2>
          <p>
            You are responsible for keeping your credentials secure. We may
            suspend accounts used for spam, harassment, or attempts to disrupt
            the service.
          </p>
        </>
      ) : (
        <>
          <h2>Sử dụng nội dung</h2>
          <p>
            Các bài viết trên Sciencepedia được phát hành theo giấy phép CC BY-SA
            4.0. Bạn được phép sao chép, chỉnh sửa và phân phối lại, kể cả cho
            mục đích thương mại, với điều kiện ghi nguồn Sciencepedia và chia sẻ
            bản phái sinh theo cùng giấy phép.
          </p>

          <h2>Đóng góp nội dung</h2>
          <p>
            Người đóng góp giữ quyền được ghi tên tác giả, đồng thời cấp cho
            Sciencepedia quyền xuất bản, biên tập và phân phối lại phần đóng góp
            theo cùng giấy phép. Vui lòng không gửi nội dung mà bạn không có
            quyền công bố.
          </p>

          <h2>Trợ lý AI</h2>
          <p>
            Câu trả lời do mô hình ngôn ngữ tạo ra và có thể thiếu sót hoặc sai.
            Hãy luôn đối chiếu với các bài viết được trích dẫn. Thông tin sức
            khoẻ trên trang chỉ mang tính tham khảo, không phải tư vấn y khoa.
          </p>

          <h2>Tài khoản</h2>
          <p>
            Bạn chịu trách nhiệm bảo mật thông tin đăng nhập của mình. Chúng tôi
            có thể khoá các tài khoản dùng để phát tán spam, quấy rối hoặc phá
            hoại dịch vụ.
          </p>
        </>
      )}
    </StaticPage>
  );
}
